language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

sudo: false

addons:
  mariadb: '10.2'

before_install:
  - sudo apt-get install -y pkg-config libssl-dev

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
