[package]
name = "liberation"
version = "0.1.0"
authors = ["Yoann Kehler <privat@yoann.de>"]

[dependencies]
rand = "~0.5"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
chrono = "~0.4"
actix-web = "~0.6.10"

[dependencies.mysql]
version = "*"
features = ["rustc-serialize"]

[dev-dependencies]
