[package]
name = "liberation"
version = "0.1.0"
authors = ["Yoann Kehler <privat@yoann.de>"]
edition = "2018"

[dependencies]
rand = "^0.7"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
chrono = {version="^0.4", features = ["serde"] }
actix-web = { version = "2.0", features = ["openssl"] }
actix-rt = "1.0"
awc = "1.0"
actix-files = "0.2"
actix = "*"
failure = "*"
futures = "0.3"
config = "^0.9"
oauth2 = "2.0.0-beta.3"
url = "^1.0"
url_serde="*"
jsonwebtoken = "^6"
log = "*"
env_logger = "*"
base64 = "*"
openssl = "^0.10"
mysql = "18.0"

[dev-dependencies]

[profile.dev]
debug = true
overflow-checks = true

[profile.test]
opt-level = 0
debug = 2
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
overflow-checks = false
