[package]
name = "liberation"
version = "0.1.0"
authors = ["Yoann Kehler <privat@yoann.de>"]

[dependencies]
rand = "0.4" 
[dependencies.mysql]
version = "*"
features = ["rustc-serialize"]

[dev-dependencies]
