[package]
name = "liberation"
version = "0.1.0"
authors = ["Yoann Kehler <privat@yoann.de>"]

[dependencies]
rand = "~0.5"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
chrono = "~0.4"
#actix-web = {git = "https://github.com/actix/actix-web", branch="master"}
actix-web = "~0.7.2"
failure = "*"
futures = "*"

[dependencies.mysql]
version = "*"
features = ["rustc-serialize"]

[dev-dependencies]
