[package]
name = "liberation"
version = "0.1.0"
authors = ["Yoann Kehler <privat@yoann.de>"]

[dependencies]
rand = "~0.5"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
chrono = "~0.4"
failure = "*"
futures = "*"
config = "0.9"
oauth2 = "2.0.0-alpha.1"
url = "*"
url_serde="*"
hyper = "0.12"


[dependencies.mysql]
version = "*"
features = ["rustc-serialize"]

[dev-dependencies]

[profile.dev]
debug = true
overflow-checks = true

[profile.test]
opt-level = 0
debug = 2
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
overflow-checks = false
