version: '3.6'

services:
    db:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=thereIsNoPassword!
            - MYSQL_DATABASE=liberation

    test-db:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=thereIsNoPassword!
            - MYSQL_DATABASE=test_liberation
        tmpfs: /var/lib/mysql
