version: '3.6'

services:
    liberation-db:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=thereIsNoPassword!
            - MYSQL_DATABASE=liberation
        ports:
            - 33061:3306

    keycloak-db:
        image: mariadb:10.2
        environment:
            - MYSQL_ROOT_PASSWORD=thereIsNoPassword!
            - MYSQL_DATABASE=keycloak
        networks:
            - keycloak-network

    test-db:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=thereIsNoPassword!
            - MYSQL_DATABASE=test_liberation
        tmpfs: /var/lib/mysql
        ports:
            - 33062:3306
    keycloak:
        image: jboss/keycloak
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_VENDOR=mariadb
            - DB_ADDR=keycloak-db
            - DB_PASSWORD=thereIsNoPassword!
            - DB_USER=root
        networks:
            - keycloak-network
        ports:
            - 8081:8080
networks:
    keycloak-network:
